scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'app'
    scrape_interval: 1m
    static_configs:
      - targets: ['app:9090']